import {atom, selector, useRecoilValue, useSetRecoilState} from "recoil";
import {Head} from "next/document";
import {Image} from 'next/image';
import styles from '../styles/Home.module.css'

const getLatestProjectVersion = async (projectId) => ({projectId: 'default id'});

export const currentProjectId = atom({
    key: 'currentProjectId',
    default: null
})

const _latestProjectVersion = atom({
    key: 'latestProjectVersion',
    default: {
        id: null,
        isAtom: true
    }
})

export const latestProjectVersionId = atom({
    key: 'latestProjectVersionId',
    default: null
})


export const latestProjectVersion = selector({
    key: 'latestProjectVersionLazyLoader',
    get: async ({get}) => {
        // get(latestProjectVersionId);
        return await getLatestProjectVersion(get(currentProjectId));
    },
    set: ({get, set}, newValue) => {
        set(_latestProjectVersion, newValue);
        set(latestProjectVersionId, newValue.id)
    },
});

export default function Home() {
    const setCurrentProjectId = useSetRecoilState(currentProjectId);
    setCurrentProjectId(123);

    const latestVersion = useRecoilValue(latestProjectVersion);
    console.log(latestVersion);
    return (
        <div>
            <Head>
                <title>Recoil Suspense Bug Reproduction</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    {JSON.stringify(latestVersion)}
                </h1>
            </main>
        </div>
    )
}
