import {Suspense} from 'react';
import {atom, selector, useRecoilValueLoadable, useSetRecoilState} from "recoil";
import Head from "next/head";
import {Image} from 'next/image';
import styles from '../styles/Home.module.css'


const getLatestProjectVersion = async (projectId) => ({projectId: projectId});

export const currentProjectId = atom({
    key: 'currentProjectId',
    default: null
})

const _latestProjectVersion = atom({
    key: 'latestProjectVersion',
    default: {
        id: null,
        isAtom: true
    }
})

export const latestProjectVersionId = atom({
    key: 'latestProjectVersionId',
    default: null
})


export const latestProjectVersion = selector({
    key: 'latestProjectVersionLazyLoader',
    get: async ({get}) => {
        // get(latestProjectVersionId);
        return await getLatestProjectVersion(get(currentProjectId));
    },
    set: ({get, set}, newValue) => {
        set(_latestProjectVersion, newValue);
        set(latestProjectVersionId, newValue.id)
    },
});

export default function Home() {
    const setCurrentProjectId = useSetRecoilState(currentProjectId);
    setCurrentProjectId(123);

    return (
        <div>
            <Head>
                <title>Recoil Suspense Bug Reproduction</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Suspense fallback={<div>Loading...</div>}>
                <main className={styles.main}>
                    <h1 className={styles.title}>
                        <HomeHelper/>
                        <button onClick={() => setCurrentProjectId(25)}>Click</button>
                    </h1>
                </main>
            </Suspense>
        </div>
    )
}

function HomeHelper(){
    const latestVersion = useRecoilValueLoadable(latestProjectVersion);

    return <div>{JSON.stringify(latestVersion.getValue().projectId)}</div>

}